<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2A8DDC6" failures="0" tests="1" name="com.weichertwm.qa.testcases.WCWM_Adding_Existing_Customer" time="22.617" errors="1" timestamp="01 Aug 2023 05:55:39 GMT" skipped="0">
  <testcase classname="com.weichertwm.qa.testcases.WCWM_Adding_Existing_Customer" name="test" time="22.617">
    <error message="User not logged into Great Gulf application successfully" type="com.weichertwm.qa.framework.FrameworkException">
      <![CDATA[com.weichertwm.qa.framework.FrameworkException: User not logged into Great Gulf application successfullyat com.weichertwm.qa.pages.LoginPage.loginToApp(LoginPage.java:46)at com.weichertwm.qa.testcases.WCWM_Adding_Existing_Customer.test(WCWM_Adding_Existing_Customer.java:27)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:578)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- com.weichertwm.qa.testcases.WCWM_Adding_Existing_Customer -->
